### ISSUE TITLE
stop using  link tags withing button tags

### ISSUE THREAD

**Issue by ngdream** [osscameroon/TypePen#2]
stop using link tags within button tags it enlarges your code and is not at all elegant, moreover if you find that the "a" tag does not work as you want why not to use the classes??

**Comment by HanslettTheDev** [comment]
Please could you explain the details of the issue?

**Comment by ngdream** [comment]
> Please could you explain the details of the issue?

 you wrote something like this 

```html
<button type="button" id="back"><a href="{{ url_for('home') }}">Back</a></button>
```
