### ISSUE TITLE
no need to create many template

### ISSUE THREAD

**Issue by ngdream** [osscameroon/TypePen#3]
is a file editor so you just have to add javascript functions to add new files , delete files  or openfile

just one template is necessary (  the editor template)

**Comment by HanslettTheDev** [comment]
Python is the main backend of this project. Javascript could have been heavily used and node could have been the preferred option. But we are using an API made in python to package this as a desktop application. Yes, they are many templates. Some unnecessary. a PR will be appreciated so we can see this in action

**Comment by ngdream** [comment]
> Python is the main backend of this project. Javascript could have been heavily used and node could have been the preferred option. But we are using an API made in python to package this as a desktop application. Yes, they are many templates. Some unnecessary. a PR will be appreciated so we can see this in action

i know python is the main language but all good softwares have a good frontend processing 😄
