### ISSUE TITLE
screenshot of the working app on  the README

### ISSUE THREAD

**Issue by Sanix-Darker** [osscameroon/TypePen#6]
It ould be great to have the screenshots of the working project in the README + a basic README on how to set it up and running, could be great to follow this template :
```

## FEATURES

## REQUIREMENTS

## HOW TO INSTALL

## HOW TO LAUNCH

## SCREENSHOTS
```

Add more interest on the README itself 🙏🏽

**Comment by HanslettTheDev** [comment]
Done!
Updated the readme thanks
