### ISSUE TITLE
pycaches/.pyc should not be versioned

### ISSUE THREAD

**Issue by Sanix-Darker** [osscameroon/TypePen#8]
## WHAT
- am proposing to add **__pycache__ directories to the ./.gitignore
- remove from the git cache those pycache

What do you think @HanslettTheDev ?

**Comment by HanslettTheDev** [comment]
yes done bro thabks

**Comment by HanslettTheDev** [comment]
The main branch hasn't been updated but as soon as i am done, i will merge thanks
